apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lunch
spec:
  rules:
  - host: lunch.u0.k8z.eu
    http:
      paths:
      - backend:
          service:
            name: lunch
            port:
              number: 80
        path: /
        pathType: Prefix
