apiVersion: apps/v1
kind: Deployment
metadata:
  name: lunch
spec:
  template:
    spec:
      containers:
      - name: lunch
        envFrom:
          - configMapRef:
              name: lunch-config