apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: simple deployment
    created.by: kubectl run lunch --image=lalyos/lunch-wto --env=TITLE=Lets
      have a lunch --env=COLOR=lightblue --port=80 --record=true --labels=app=lunch
      --dry-run=true --output=yaml
  labels:
    app: lunch
  name: lunch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lunch
  strategy: {}
  template:
    metadata:
      labels:
        app: lunch
    spec:
      containers:
      - name: lunch
        image: lalyos/lunch-wto
        ports:
        - containerPort: 80
        resources: {}
